In [ ]:
import pandas as pd
df=pd.read_excel('/content/Dot_and_Key_Brand_Launch_Intelligence_Dataset.xlsx')
print('rows:',df.shape[0])
print('columns:',df.shape[1])
df.head()

rows: 10000
columns: 24

,Order_ID,Customer_ID,Order_Date,Age,Gender,City,Customer_Segment,Customer_Type,Product,Category,...,Campaign,Impressions,Clicks,Leads,Conversions,Ad_Spend,Revenue,Product_Cost,Shipping_Cost,Profit
0,ORD001421,CUST00399,2025-01-01,49,Female,Bhubaneswar,Growth,Returning,Body Lotion,Body Care,...,Retargeting,23111,1116,139,39,584.97,1509.64,845.22,62.87,16.58
1,ORD007153,CUST02073,2025-01-01,45,Female,Bhubaneswar,New Customer,New,Cream Blush,Makeup,...,Summer Glow,10668,442,88,25,648.35,1769.21,1013.35,65.54,41.97
2,ORD007118,CUST02007,2025-01-01,41,Female,Jaipur,New Customer,New,Hydra Moisturizer,Skincare,...,Festive Beauty,4427,144,23,5,16.53,1921.51,1004.35,79.86,820.77
3,ORD004303,CUST00094,2025-01-01,36,Female,Kolkata,New Customer,New,Cream Blush,Makeup,...,Summer Glow,8580,134,24,5,56.49,600.73,261.88,41.98,240.38
4,ORD004896,CUST02795,2025-01-01,47,Female,Kolkata,Growth,Returning,Hydra Moisturizer,Skincare,...,Festive Beauty,22396,856,28,4,855.57,1278.15,795.24,71.34,-444.00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order_ID           10000 non-null  object
 1   Customer_ID        10000 non-null  object
 2   Order_Date         10000 non-null  datetime64[ns]
 3   Age                10000 non-null  int64
 4   Gender             10000 non-null  object
 5   City               10000 non-null  object
 6   Customer_Segment   10000 non-null  object
 7   Customer_Type      10000 non-null  object
 8   Product            10000 non-null  object
 9   Category           10000 non-null  object
 10  Unit_Price         10000 non-null  int64
 11  Quantity           10000 non-null  int64
 12  Discount_Pct       10000 non-null  int64
 13  Marketing_Channel  10000 non-null  object
 14  Campaign           10000 non-null  object
 15  Impressions        10000 non-null  int64
 16  Clicks             10000 non-null  int64
 17  Leads              10000 non-null  int64
 18  Conversions        10000 non-null  int64
 19  Ad_Spend           10000 non-null  float64
 20  Revenue            10000 non-null  float64
 21  Product_Cost       10000 non-null  float64
 22  Shipping_Cost      10000 non-null  float64
 23  Profit             10000 non-null  float64
dtypes: datetime64[ns](1), float64(5), int64(8), object(10)
memory usage: 1.8+ MB

In [ ]:
df['Order_ID'].duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

Order_ID             0
Customer_ID          0
Order_Date           0
Age                  0
Gender               0
City                 0
Customer_Segment     0
Customer_Type        0
Product              0
Category             0
Unit_Price           0
Quantity             0
Discount_Pct         0
Marketing_Channel    0
Campaign             0
Impressions          0
Clicks               0
Leads                0
Conversions          0
Ad_Spend             0
Revenue              0
Product_Cost         0
Shipping_Cost        0
Profit               0
dtype: int64

In [ ]:
df.describe()

,Order_Date,Age,Unit_Price,Quantity,Discount_Pct,Impressions,Clicks,Leads,Conversions,Ad_Spend,Revenue,Product_Cost,Shipping_Cost,Profit
count,10000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2025-09-29 19:01:55.200000,36.563900,704.255000,1.673000,10.187000,12711.62480,443.802600,71.075400,12.355100,349.158303,1056.565149,528.152414,57.243758,122.010674
min,2025-01-01 00:00:00,18.000000,449.000000,1.000000,0.000000,800.00000,4.000000,1.000000,1.000000,15.040000,315.840000,144.070000,30.010000,-867.010000
25%,2025-05-18 00:00:00,27.000000,499.000000,1.000000,5.000000,6552.75000,181.000000,25.000000,3.000000,142.170000,600.450000,297.942500,43.520000,-140.030000
50%,2025-09-30 00:00:00,37.000000,649.000000,2.000000,10.000000,12794.00000,377.000000,54.000000,8.000000,241.805000,889.110000,445.460000,57.080000,101.700000
75%,2026-02-12 00:00:00,46.000000,799.000000,2.000000,15.000000,18674.25000,649.000000,100.000000,17.000000,549.790000,1364.132500,687.637500,71.060000,355.195000
max,2026-06-30 00:00:00,55.000000,1099.000000,3.000000,25.000000,24999.00000,1901.000000,438.000000,123.000000,949.690000,3544.350000,1910.720000,85.000000,2181.680000
std,NaN,11.021028,205.212929,0.749351,7.694865,7007.80595,320.212493,61.053593,12.620441,260.838278,588.716197,304.684003,15.842364,421.421712

In [ ]:
loss_orders=df[df['Profit']<0]
print("loss making orders:", len(loss_orders))
print("loss making orders percentage:",round(len(loss_orders)/len(df) * 100 ,2),"%")

loss making orders: 3758
loss making orders percentage: 37.58 %

In [ ]:
channel_analysis=df.groupby('Marketing_Channel')[['Revenue','Ad_Spend','Profit']].sum()
channel_analysis

                      Revenue    Ad_Spend     Profit
Marketing_Channel
Affiliate          1166616.32   142950.30  371004.78
Email              1437246.76   180206.80  465463.46
Google Ads         2121887.65  1078961.94 -130636.35
Influencer         1434279.19   522098.23  114910.22
Instagram Ads      2652086.67  1351752.32 -170437.99
Organic Search     1753534.90   215613.44  569802.62

In [ ]:
import pandas as pd

df = pd.read_excel("/content/Dot_and_Key_Brand_Launch_Intelligence_Dataset.xlsx")

print("Dataset loaded!")

Dataset loaded!

In [ ]:
import sqlite3
conn = sqlite3.connect("/content/dot_key_marketing.db")
df.to_sql("orders", conn, if_exists='replace', index=False)
print('SQL database created successfully')

SQL database created successfully

In [ ]:
query= """
SELECT Marketing_Channel,
SUM(Revenue) AS Total_Revenue,
    SUM(Ad_Spend) AS Total_Ad_Spend,
    SUM(Profit) AS Total_Profit
FROM orders
GROUP BY Marketing_Channel
ORDER BY Total_Revenue DESC
"""
Channel_revenue = pd.read_sql_query(query,conn)
Channel_revenue

  Marketing_Channel  Total_Revenue  Total_Ad_Spend  Total_Profit
0     Instagram Ads     2652086.67      1351752.32    -170437.99
1        Google Ads     2121887.65      1078961.94    -130636.35
2    Organic Search     1753534.90       215613.44     569802.62
3             Email     1437246.76       180206.80     465463.46
4        Influencer     1434279.19       522098.23     114910.22
5         Affiliate     1166616.32       142950.30     371004.78

In [ ]:
from numpy import prod
Query ="""
SELECT Product,Category,
SUM(Revenue) AS Total_Revenue,
SUM(Ad_Spend) AS Total_Ad_Spend,
SUM(Profit) AS Total_Profit
FROM orders
GROUP BY Product,Category
ORDER BY Total_Revenue DESC
"""
product_analysis = pd.read_sql_query(Query,conn)
product_analysis

              Product   Category  Total_Revenue  Total_Ad_Spend  Total_Profit
0  Night Repair Cream   Skincare     2066127.85       436334.53     528832.23
1          Glow Serum   Skincare     1624611.85       428105.02     311627.47
2    SPF 50 Sunscreen   Sun Care     1478026.62       432357.98     238108.20
3   Hydra Moisturizer   Skincare     1319616.72       439581.83     144633.29
4         Cream Blush     Makeup     1224227.39       425549.83     115124.29
5         Body Lotion  Body Care     1062289.37       467927.18      -7593.97
6            Lip Tint     Makeup      949931.33       430292.37     -28591.14
7           Face Wash   Skincare      840820.36       431434.29     -82033.63

In [ ]:
query ="""
SELECT Customer_segment,
COUNT(DISTINCT Customer_ID) AS Unique_Customers,
SUM(Revenue) AS Total_Revenue,
    SUM(Profit) AS Total_Profit,
    AVG(Revenue) AS Average_Order_Value
FROM orders
GROUP BY Customer_segment
ORDER BY Unique_Customers DESC
"""
Segment_analysis = pd.read_sql_query(query,conn)
Segment_analysis

,Customer_Segment,Unique_Customers,Total_Revenue,Total_Profit,Average_Order_Value
0,Growth,1846,2990098.88,360429.05,1055.825876
1,Occasional,1833,2989383.61,339011.91,1052.970627
2,New Customer,1754,2801175.74,313918.71,1048.344214
3,High Value,1286,1784993.26,206747.07,1077.243971

In [ ]:
query = """
SELECT
    Marketing_Channel,
    SUM(Revenue) AS Total_Revenue,
    SUM(Ad_Spend) AS Total_Ad_Spend,
    ROUND(SUM(Revenue)/SUM(Ad_Spend),2) AS ROAS
FROM orders
GROUP BY Marketing_Channel
ORDER BY ROAS DESC;
"""

roas_analysis = pd.read_sql_query(query, conn)

roas_analysis

  Marketing_Channel  Total_Revenue  Total_Ad_Spend  ROAS
0         Affiliate     1166616.32       142950.30  8.16
1    Organic Search     1753534.90       215613.44  8.13
2             Email     1437246.76       180206.80  7.98
3        Influencer     1434279.19       522098.23  2.75
4        Google Ads     2121887.65      1078961.94  1.97
5     Instagram Ads     2652086.67      1351752.32  1.96

In [ ]:
query = """
SELECT
    Campaign,
    SUM(Impressions) AS Total_Impressions,
    SUM(Clicks) AS Total_Clicks,
    SUM(Leads) AS Total_Leads,
    SUM(Conversions) AS Total_Conversions,
   ROUND(SUM(Conversions)*100.0/SUM(Clicks),2) AS Conversion_Rate
   FROM orders
   GROUP BY Campaign
   ORDER BY Conversion_Rate DESC
"""

campaign_analysis = pd.read_sql_query(query, conn)

campaign_analysis

,Campaign,Total_Impressions,Total_Clicks,Total_Leads,Total_Conversions,Conversion_Rate
0,Summer Glow,21528186,741909,119781,21081,2.84
1,Everyday Essentials,20429801,703914,113078,19698,2.80
2,New Launch,21140129,737917,119075,20535,2.78
3,Retargeting,20850443,734783,116247,20319,2.77
4,Loyalty,21015975,743874,118573,20622,2.77
5,Festive Beauty,22151714,775629,124000,21296,2.75

In [ ]:
product_profit=df.groupby('Product')['Profit'].sum().sort_values(ascending=False)
product_profit

Product
Night Repair Cream    528832.23
Glow Serum            311627.47
SPF 50 Sunscreen      238108.20
Hydra Moisturizer     144633.29
Cream Blush           115124.29
Body Lotion            -7593.97
Lip Tint              -28591.14
Face Wash             -82033.63
Name: Profit, dtype: float64

In [ ]:
segment_profit = (
    df.groupby("Customer_Segment")["Profit"]
    .sum()
    .sort_values(ascending=False)
)

segment_profit

Customer_Segment
Growth          360429.05
Occasional      339011.91
New Customer    313918.71
High Value      206747.07
Name: Profit, dtype: float64

In [ ]:
channel_performance=df.groupby('Marketing_Channel')[['Revenue','Ad_Spend','Profit']].sum()
channel_performance['ROAS']=round(channel_performance['Profit']/channel_performance['Ad_Spend'],2)
channel_performance.sort_values(by='ROAS',ascending=False)

                      Revenue    Ad_Spend     Profit  ROAS
Marketing_Channel
Organic Search     1753534.90   215613.44  569802.62  2.64
Affiliate          1166616.32   142950.30  371004.78  2.60
Email              1437246.76   180206.80  465463.46  2.58
Influencer         1434279.19   522098.23  114910.22  0.22
Google Ads         2121887.65  1078961.94 -130636.35 -0.12
Instagram Ads      2652086.67  1351752.32 -170437.99 -0.13

In [ ]:
city_performance = (
    df.groupby("City")[["Revenue", "Profit"]]
    .sum()
    .sort_values("Revenue", ascending=False)
)

city_performance.head(10)

                Revenue     Profit
City
Delhi        1103461.72  131703.72
Ahmedabad    1096643.71  150346.93
Bengaluru    1082425.58  136857.95
Hyderabad    1078587.48  133249.02
Mumbai       1071273.89  112200.52
Kolkata      1066919.31  129160.64
Pune         1028049.13  116678.79
Bhubaneswar  1022818.64  106950.67
Chennai      1011949.97   95383.64
Jaipur       1003522.06  107574.86

In [ ]:
customer_type_performance = (
    df.groupby("Customer_Type")[["Revenue", "Profit", "Quantity"]]
    .sum()
    .sort_values("Revenue", ascending=False)
)

customer_type_performance

                  Revenue     Profit  Quantity
Customer_Type
Returning      7764475.75  906188.03     12332
New            2801175.74  313918.71      4398

In [ ]:
campaign_funnel = (
    df.groupby("Campaign")[["Impressions", "Clicks", "Leads", "Conversions"]]
    .sum()
    .sort_values("Conversions", ascending=False)
)

campaign_funnel

                     Impressions  Clicks   Leads  Conversions
Campaign
Festive Beauty          22151714  775629  124000        21296
Summer Glow             21528186  741909  119781        21081
Loyalty                 21015975  743874  118573        20622
New Launch              21140129  737917  119075        20535
Retargeting             20850443  734783  116247        20319
Everyday Essentials     20429801  703914  113078        19698

In [ ]:
campaign_funnel["CTR"] = (
    campaign_funnel["Clicks"] / campaign_funnel["Impressions"] * 100
).round(2)

campaign_funnel["Lead_Rate"] = (
    campaign_funnel["Leads"] / campaign_funnel["Clicks"] * 100
).round(2)

campaign_funnel["Conversion_Rate"] = (
    campaign_funnel["Conversions"] / campaign_funnel["Clicks"] * 100
).round(2)

campaign_funnel

,Impressions,Clicks,Leads,Conversions,CTR,Lead_Rate,Conversion_Rate
Campaign,,,,,,,
Festive Beauty,22151714,775629,124000,21296,3.50,15.99,2.75
Summer Glow,21528186,741909,119781,21081,3.45,16.14,2.84
Loyalty,21015975,743874,118573,20622,3.54,15.94,2.77
New Launch,21140129,737917,119075,20535,3.49,16.14,2.78
Retargeting,20850443,734783,116247,20319,3.52,15.82,2.77
Everyday Essentials,20429801,703914,113078,19698,3.45,16.06,2.80

In [ ]:
loss_by_product = (
    df[df["Profit"] < 0]
    .groupby("Product")["Profit"]
    .sum()
    .sort_values()
)

loss_by_product

Product
Face Wash            -198743.56
Lip Tint             -178077.11
Body Lotion          -176961.32
Hydra Moisturizer    -129793.12
Cream Blush          -128427.83
SPF 50 Sunscreen      -99670.61
Glow Serum            -86139.88
Night Repair Cream    -59260.17
Name: Profit, dtype: float64

In [ ]:
marketing_summary = {
    "Total Revenue": df["Revenue"].sum(),
    "Total Profit": df["Profit"].sum(),
    "Total Ad Spend": df["Ad_Spend"].sum(),
    "Total Orders": df["Order_ID"].nunique(),
    "Total Customers": df["Customer_ID"].nunique(),
    "Total Conversions": df["Conversions"].sum(),
    "Overall ROAS": round(df["Revenue"].sum() / df["Ad_Spend"].sum(), 2)
}

marketing_summary

{'Total Revenue': np.float64(10565651.490000002),
 'Total Profit': np.float64(1220106.74),
 'Total Ad Spend': np.float64(3491583.0300000003),
 'Total Orders': 10000,
 'Total Customers': 2877,
 'Total Conversions': np.int64(123551),
 'Overall ROAS': np.float64(3.03)}